### ISSUE TITLE
Improve syntax to compute probabilistic queries and obtain the result as a non-probabilistic table

### ISSUE THREAD

**Issue by demianw** [NeuroLang/NeuroLang#432]
- [x] `Q(x, y, prob(x, y)) :- phi(x, y) == SUCC(phi(x,y))`
- [x] `Q(x, y, w, z, prob(x, y)) :- phi(x, y, w, z) == MARG(phi(x,y, _, _) | phi(_, _, w, z))`

**Comment by tgy** [comment]
We now have the MARG syntax. I believe this can be closed?
