### ISSUE TITLE
Choose probabilistic solver based on query complexity

### ISSUE THREAD

**Issue by tgy** [NeuroLang/NeuroLang#480]
For hierarchical queries and queries with non-shatterable self-joins, we should revert to a knowledge compilation -based resolution. This should be the default behaviour. Currently, we only use one solver (chosen at the frontend level when instantiating the frontend).

**Comment by demianw** [comment]
Was this solved?

**Comment by tgy** [comment]
i think your recent PR fixed this. i'll let you close
