### ISSUE TITLE
relational algebra optimisation through optimal join order

### ISSUE THREAD

**Issue by tgy** [NeuroLang/NeuroLang#509]
Let `A`, `B` and `C` be three named relations for which we wish to calculate `A ⋈ B ⋈ C`.
Sometimes, it is much faster to calculate `A ⋈ (B ⋈ C)` than to calculate `(A ⋈ B) ⋈ C`. For example if `A ⋈ B` results in a very large relation and `B ⋈ C` results in a smaller relation such that `A ⋈ (B ⋈ C)` becomes tractable.

An example of this is if `A = B = VoxelReported` and `C = SeedVoxel`, where `VoxelReported` is a very large relation and `SeedVoxel` is a very small relation such that `VoxelReported ⋈ SeedVoxel` results in a much smaller relation than `VoxelReported`.
`(VoxelReported ⋈ VoxelReported) ⋈ SeedVoxel` is intractable but `VoxelReported ⋈ (VoxelReported ⋈ SeedVoxel)` is tractable.

Currently, from one query resolution to another, the order of the join operation is random (i.e. sometimes the resolution terminates because the order of the joins happens to do `VoxelReported ⋈ SeedVoxel` first, but other times the resolution attempts to calculate `VoxelReported ⋈ VoxelReported` which leads to too much memory being used and the program being killed).

What would be the best approach to implement this kind of optimisation?

**Comment by demianw** [comment]
Being handled by #587
