### ISSUE TITLE
Comfort API for list of single elements raises ValueError

### ISSUE THREAD

**Issue by LouisRouillard** [NeuroLang/NeuroLang#516]
```
from neurolang import frontend
neurolang = frontend.NeurolangDL()
neurolang.add_tuple_set(range(10), int)
```
Fails with `ValueError: Not <class 'int'> is not a generic type` where it should return an `AbstractSet[int]` symbol.
Note that test https://github.com/NeuroLang/NeuroLang/blob/418da27d2b0f4b7642139ed1f475002583856a2c/neurolang/frontend/tests/test_frontend.py#L113-L121 incoherently does run.

**Comment by demianw** [comment]
Problem is on the `__repr__` implementation
