### ISSUE TITLE
Add support for probabilistic boolean queries

### ISSUE THREAD

**Issue by tgy** [NeuroLang/NeuroLang#523]
Currently, only set-based probabilistic queries are implemented and tested.

It should not be too hard to also support **boolean** queries, given that we already support **set-based** queries.

This would make it possible to solve queries such as `query() :- Z(y)` where `y` is existentially quantified.

**Comment by demianw** [comment]
@tgy this has been solved, hasn't it?

**Comment by tgy** [comment]
It seems to be! I added a small test here https://github.com/NeuroLang/NeuroLang/pull/631 and it passes
