### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by tgy** [NeuroLang/NeuroLang#574]
https://github.com/NeuroLang/NeuroLang/blob/0984fd887e99960ad6453709c451e986d6780969/neurolang/relational_algebra_provenance.py#L300

Maybe I'm wrong but my understanding is that this line does not do anything as `symmetric_difference` returns a new set

**Comment by demianw** [comment]
@gzanitti ?

**Comment by gzanitti** [comment]
Oh, yes, my mistake. It's dead code that I forgot to remove. Sorry 😐
