### ISSUE TITLE
Optimise RelationalAlgebraSet implementation

### ISSUE THREAD

**Issue by jonasrenault** [NeuroLang/NeuroLang#587]
Currently AbstractRelationalAlgebraSet has only one in-memory implementation based on pandas. Optimisation could be achieved by providing an implementation relying on an SQL database instead. An abstraction layer such as SQLAlchemy could be used to abstract the SQL database being used but would still require cumbersome installation of an SQL database by the user. Performance gain when run on SQLite is minimal as indicated by  @demianw.

- [ ] A first step towards optimisation could be to start by using modin (http://modin.org/) to improve performance of the pandas implementation.
- [ ] Benchmark tests should be created to evaluate the performance of the various RelationalAlgebraSet implementations.

**Comment by demianw** [comment]
@gzanitti had considered vaex (https://vaex.io/docs/) instead of modin, but I think that modin seems like a more flexible platform than vaex.

**Comment by demianw** [comment]
@jonasrenault a good benchmark on the performance of these on the next step is to run the chase benchmark `TimeChase` while changing the implementation of the relational algebra sets in the datalog.wrapped_collections module:
https://github.com/NeuroLang/NeuroLang/blob/bc2790fd499d2663f36a6c2c0a2f4f46bb76f5e1/neurolang/datalog/wrapped_collections.py#L13
