### ISSUE TITLE
Get rid of NeuroSynth library dependency as it seems to not be maintained anymore

### ISSUE THREAD

**Issue by demianw** [NeuroLang/NeuroLang#590]
Currently we depend on the Neurosynth library https://github.com/NeuroLang/NeuroLang/blob/bc6acb71fbb8700bd8df2afe951eed47b349b2a1/neurolang/frontend/neurosynth_utils.py#L25 . However, this could be changed for direct access to the database as it's done in https://github.com/NeuroLang/NeuroLang/blob/bc6acb71fbb8700bd8df2afe951eed47b349b2a1/examples/plot_neurosynth_implementation.py#L31

This will help as NeuroSynth seems to not be maintained anymore.

**Comment by jonasrenault** [comment]
Also, Neurosynth (& NeuroQuery) have updated their data repository so scripts to fetch Neurosynth / Neuroquery databases need to be updated.
See [https://github.com/neurosynth/neurosynth-data/pull/6](https://github.com/neurosynth/neurosynth-data/pull/6)
