### ISSUE TITLE
Group By implementation in RA sets does not work with an empty as input

### ISSUE THREAD

**Issue by demianw** [NeuroLang/NeuroLang#642]
```python
from neurolang.utils.relational_algebra_set import NamedRelationalAlgebraFrozenSet
ras = NamedRelationalAlgebraFrozenSet(columns=tuple())
res = ras.aggregate(('a',), ('b', 'b', sum))
```

Note that with projection, for instance, it works
```python
from neurolang.utils.relational_algebra_set import NamedRelationalAlgebraFrozenSet
ras = NamedRelationalAlgebraFrozenSet(columns=tuple())
res = ras.projection(('a',))
```

we need every operation to work with the empty, dee, and dum sets. This became a problem with the new implementation of aggregation in the intermediate representation

**Comment by jonasrenault** [comment]
Aggregation on empty sets with arity > 0 already works, provided the groupby and aggregate columns are valid.
```python
ras = NamedRelationalAlgebraFrozenSet(columns=tuple('a', 'b'))
res = ras.aggregate(('a',), [('b', 'b', sum)])
assert res == NamedRelationalAlgebraFrozenSet(columns=('a', 'b')) #True
```

On dum() sets, I expect the result of an aggregation should be an empty set with columns = (groupby_cols) + (aggregate_destination_cols).
```python
ras = NamedRelationalAlgebraFrozenSet(columns=tuple())
res = ras.aggregate(('a',), [('b', 'b', sum)])
assert res == NamedRelationalAlgebraFrozenSet(columns=('a', 'b')) #True
```

What is the expected output for aggregation on dee sets ? For the extended projection, it returns a set with 0 values :

```python
ras = NamedRelationalAlgebraFrozenSet.dee()
res = ras.extended_projection({'x': sum})
assert res == NamedRelationalAlgebraFrozenSet(('x'), [[0]]) #True
```

Is this valid ? or should it return an empty set with the projected columns ? What about aggregation ?

**Comment by demianw** [comment]
Good point, I think that it's OK if it's throws an exception.
